export const ResizeModuleConfig = {
    modules: [
        'DisplaySize',
        'Toolbar',
        'Resize',
    ],
    overlayStyles: {
        position: 'absolute',
        boxSizing: 'border-box',
        border: `1px dashed hsl(var(--muted-foreground))`,
        borderRadius: 'var(--radius)',
    },
    handleStyles: {
        position: 'absolute',
        height: '10px',
        width: '10px',
        backgroundColor: 'hsl(var(--background))',
        border: '1px solid hsl(var(--border))',
        borderRadius: '50%',
        boxSizing: 'border-box',
        opacity: '0.9',
    },
    displayStyles: {
        position: 'absolute',
        fontFamily: 'var(--font-sans)',
        fontSize: '12px',
        lineHeight: '1.2',
        padding: '4px 8px',
        textAlign: 'center',
        backgroundColor: 'hsl(var(--card))',
        color: 'hsl(var(--card-foreground))',
        border: '1px solid hsl(var(--border))',
        borderRadius: 'var(--radius)',
        boxSizing: 'border-box',
        opacity: '0.95',
        cursor: 'default',
        boxShadow: '0 2px 6px hsl(var(--muted-foreground)), 0 0 0 1px hsl(var(--muted))',
    },
    toolbarStyles: {
        position: 'absolute',
        top: '-12px',
        right: '0',
        left: '0',
        height: '0',
        minWidth: '100px',
        fontFamily: 'var(--font-sans)',
        fontSize: '12px',
        lineHeight: '1.2',
        textAlign: 'center',
        color: 'hsl(var(--foreground))',
        boxSizing: 'border-box',
        cursor: 'default',
    },
    toolbarButtonStyles: {
        display: 'inline-block',
        width: '24px',
        height: '24px',
        background: 'hsl(var(--background))',
        border: '1px solid hsl(var(--border))',
        borderRadius: 'var(--radius)',
        verticalAlign: 'middle',
        marginLeft: '2px',
        marginRight: '2px',
        padding: '2px',
        transition: 'all 0.2s ease',
    },
    toolbarButtonSvgStyles: {
        fill: 'hsl(var(--foreground))',
        stroke: 'hsl(var(--foreground))',
        strokeWidth: '1.5',
    },
};